server:
  port: 8080
  servlet:
    context-path: /api/v1
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5477/postgres
    username: postgres
    password: admin

  jpa:
    database: postgresql
    open-in-view: false
    properties:
      hibernate:
        default_schema: public
        jdbc:
          time_zone: UTC
        ddl-auto: none
system-param:
  secret-key: 5970337336763979244226452948404D6351665468576D5A7134743777217A25
  aws-active: false
  aws-access-key: AKIAULAR7BW
  aws-secret-key: rvHELsfbo4xAWnlGRXoCs4ly/c9F
  sender-email: zhiyu_zhao7@163.com
  base-url: http://localhost:8080/api/v1

