server:
  port: 8080
  servlet:
    context-path: /api/v1
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://houzezdbuat.caogumlx5xdk.ap-southeast-2.rds.amazonaws.com:5432/postgres
    username: houzezusername
    password: ${RDS_PASSWORD:username}

  jpa:
    database: postgresql
    open-in-view: false
    properties:
      hibernate:
        default_schema: public
        jdbc:
          time_zone: UTC
        ddl-auto: none
system-param:
  secret-key: 5970337336763979244226452948404D6351665468576D5A7134743777217A25
  aws-active: false
  aws-access-key: AKIAULAR7BW
  aws-secret-key: rvHELsfbo4xAWnlGRXoCs4ly/c9F
  sender-email: zhiyu_zhao7@163.com
  base-url: http://houzez4u.com
  sign-in-jwt-expired-minute: 3600
cors:
  allowed-origins: "http://houzez4u.com"
  allowed-methods: "*"
  allowed-headers: "*"


