ALTER TABLE "property"
ALTER COLUMN indoor TYPE VARCHAR(1024);
ALTER TABLE "property"
ALTER COLUMN outdoor TYPE VARCHAR(1024);
ALTER TABLE "property"
ALTER COLUMN description TYPE VARCHAR(1024);
ALTER TABLE "property"
ALTER COLUMN title TYPE VARCHAR(1024);